jobs:
- job: VS_Latest
  variables:
    ANDROID_NDK_HOME: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    ANDROID_NDK_PATH: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    AndroidNdkDirectory: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  pool:
    vmImage: 'windows-2022'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 2.2.x'
    retryCountOnTaskFailure: 3
    inputs:
      packageType: sdk
      version: 2.2.x

  - task: UseDotNet@2
    displayName: 'Use .NET 6.0.x'
    retryCountOnTaskFailure: 3
    inputs:
      packageType: sdk
      version: 6.0.x

  - task: nventiveCanaryUpdater@5
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries')
    inputs:
      solution: src
      usePrivateFeed: false
      useNuGetOrg: true
      mergeBranch: true
      branchToMerge: 'master'
      nugetUpdaterVersion: '2.3.0-alpha.35'
      allowDowngrade: true
      packageAuthor: 'nventive,uno platform'
      summaryFile: '$(Build.ArtifactStagingDirectory)/Canary.md'
      resultFile: '$(Build.ArtifactStagingDirectory)/update_result.json'

  - task: MSBuild@1
    inputs:
      solution: src\**\*.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /p:AotAssemblies=false /ds
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: drop
      publishLocation: Container
